# .github/workflows/deploy-log-retrieval.yml
name: Deploy Retrieve Logs Lambda (Dev)

on:
  push:
    branches: [workflows]
  # workflow_dispatch:

env:
  CHANNEL_ID: "C08T7JCKXEY"
  ENV: "DEV"
  LAMBDA_SERVICE: "Retrieve-logs-lambda"

jobs:
  test-lint-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies for lint/test/scan
        run: |
          pip install -r get_log/requirements.txt
          pip install pytest flake8 bandit

      - name: Lint Lambda code
        run: flake8 get_log/

      - name: Security scan Lambda code
        run: bandit -r get_log/ --exclude get_log/tests/

      - name: Run unit tests
        run: PYTHONPATH=. pytest get_log/

  deploy:
    runs-on: ubuntu-latest
    needs: test-lint-scan
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME_GITHUB }}
          aws-region: us-east-1

      - name: Install Lambda dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target ./package -r get_log/requirements.txt

      - name: Package Lambda function
        run: |
          cd package
          zip -r ../retrieve_logs.zip .
          cd ..
          zip -j retrieve_logs.zip get_log/*.py

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name dev-retrieve-logs \
            --zip-file fileb://retrieve_logs.zip

      - name: Slack Notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: DeployNotification
          SLACK_TITLE: Lambda Deployment
          SLACK_MESSAGE: 'Deployment success in ${{ env.ENV }} for ${{ env.LAMBDA_SERVICE }}'
          SLACK_COLOR: good
          SLACK_FOOTER: ${{ github.repository }} | ${{ github.ref }} | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run>
          SLACK_ICON_EMOJI: ':rocket:'

      - name: Slack Notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: DeployNotification
          SLACK_TITLE: Lambda Deployment
          SLACK_MESSAGE: 'Deployment error in ${{ env.ENV }} for ${{ env.LAMBDA_SERVICE }}'
          SLACK_COLOR: danger
          SLACK_FOOTER: ${{ github.repository }} | ${{ github.ref }} | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run>
          SLACK_ICON_EMOJI: ':x:'

      - name: Print event JSON
        run: echo "${{ toJson(github.event) }}"