name: Deploy ingest_logs Lambda (dev)

on:
  push:
    branches: [workflows]
  # workflow_dispatch:

env:
  CHANNEL_ID: "C08T7JCKXEY"

jobs:
  test_lint_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies for lint/test/scan
        run: |
          pip install -r write_log/requirements.txt
          pip install pytest flake8 bandit

      - name: Lint Lambda code
        run: flake8 write_log/

      - name: Security scan Lambda code
        run: bandit -r write_log/ --exclude write_log/tests/

      - name: Run unit tests
        run: PYTHONPATH=. pytest write_log/

  deploy:
    runs-on: ubuntu-latest
    needs: test_lint_scan
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME_GITHUB }}
          aws-region: us-east-1

      - name: Install Lambda dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target ./package -r write_log/requirements.txt

      - name: Package Lambda function
        run: |
          cd package
          zip -r ../ingest_logs.zip .
          cd ..
          zip -j ingest_logs.zip write_log/*.py

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name dev-logging-service-ingest-logs \
            --zip-file fileb://ingest_logs.zip

                    }
                  ]
                }
              ]
            
      - name: Slack Success Notification
        if: success()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*${{ github.actor }}*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Ref*\n${{ github.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event*\n${{ github.event_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Actions URL*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|build-and-deploy-dev-logging-service-ingest-logs>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Message*\nDeployment success in for dev-logging-service-ingest-logs"
                    }
                  ]
                }
              ]
            }

      - name: Slack Failure Notification
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*${{ github.actor }}*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Ref*\n${{ github.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event*\n${{ github.event_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Actions URL*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|build-and-deploy-dev-logging-service-ingest-logs>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Message*\n:x: Deployment failed in for dev-logging-service-ingest-logs"
                    }
                  ]
                }
              ]
            }
