name: Deploy ingest_logs Lambda (dev)

on:
  push:
    branches: [workflows]
  # workflow_dispatch:

env:
  CHANNEL_ID: "C08T7JCKXEY"

jobs:
  test_lint_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies for lint/test/scan
        run: |
          pip install -r write_log/requirements.txt
          pip install pytest flake8 bandit

      - name: Lint Lambda code
        run: flake8 write_log/

      - name: Security scan Lambda code
        run: bandit -r write_log/ --exclude write_log/tests/

      - name: Run unit tests
        run: PYTHONPATH=. pytest write_log/

  deploy:
    runs-on: ubuntu-latest
    needs: test_lint_scan
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME_GITHUB }}
          aws-region: us-east-1

      - name: Install Lambda dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target ./package -r write_log/requirements.txt

      - name: Package Lambda function
        run: |
          cd package
          zip -r ../ingest_logs.zip .
          cd ..
          zip -j ingest_logs.zip write_log/*.py

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name dev-logging-service-ingest-logs \
            --zip-file fileb://ingest_logs.zip

      - name: Slack Success Notification
        if: success()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.CHANNEL_ID }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":white_check_mark: ingest_logs Lambda deployed to DEV",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployed by:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                }
              ]
            }

      - name: Slack Failure Notification
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.CHANNEL_ID }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":x: ingest_logs Lambda deployment FAILED in DEV",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployed by:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                }
              ]
            }
